format_code_in_doc_comments = true
doc_comment_code_block_width = 100
imports_indent = "Block"
imports_layout = "Vertical"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
edition = "2021"
unstable_features = true
